services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: 'composer install && npm install && npm run prod'
    startCommand: 'php artisan serve --host=0.0.0.0 --port=80'
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    autoDeploy: true
    regions:
      - us
